name: Build MediaInfoKeeper

on:
  push:
    paths:
      - "MediaInfoKeeper.csproj"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore MediaInfoKeeper.csproj
 
      - name: Read version
        id: read_version
        shell: bash
        run: |
          app_version=$(cat MediaInfoKeeper.csproj | sed -ne "s/.*<AssemblyVersion>\\(.*\\)<\\/AssemblyVersion>.*/\\1/p")
          echo "app_version=$app_version" >> $GITHUB_ENV

      - name: Install ilrepack tool
        run: dotnet tool install -g dotnet-ilrepack --version 2.0.44

      - name: Build
        run: dotnet build MediaInfoKeeper.csproj -c Release --no-restore

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          name: MediaInfoKeeper v${{ env.app_version }}
          tag_name: v${{ env.app_version }}-dev.${{ github.run_number }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          overwrite_files: true
          files: Build/bin/Release/net8.0/MediaInfoKeeper.dll